name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.64.0'
    - name: Build
      run: hugo --minify
    - run: cp ./CNAME ./public
    - run: cp ./ads.txt ./public
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY:   Hzllaga/wtfsec.org 
        PUBLISH_BRANCH: master
        publish_dir: ./public
